"""add review flags to imported transactions

Revision ID: 4d5d092bfa02
Revises: f00e63f0a035
Create Date: 2026-06-04 23:21:37.558949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5d092bfa02'
down_revision: Union[str, Sequence[str], None] = 'f00e63f0a035'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imported_transactions', sa.Column('is_reviewed', sa.Boolean(), nullable=False))
    op.add_column('imported_transactions', sa.Column('is_posted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('imported_transactions', 'is_posted')
    op.drop_column('imported_transactions', 'is_reviewed')
    # ### end Alembic commands ###
